# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8723ac877459d5dc2da4ff20b601176ba444f2ed2c9f700423b98d5acd251b24c66b44f4f7d3571693eff876faf7de73aff42373aabc5baf2fe85c09bb4bc986

test:
  secret_key_base: bbb8f43ec939af8e08e54e98a2ecfa7933ec144dca6a7357b80e390b202e3f9414c707abac48ca06d3dd6a70fb6cc07aae3095bcbf4c57bf8d467f610ad40905

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
